### ISSUE TITLE
Exception: Error: could not match input

### ISSUE THREAD

**Issue by raleighr3** [aefimov/idea-batch#20]
Error message:
org.intellij.lang.batch.lexer._BatchLexer: Error: could not match input

Details:
```java
org.intellij.lang.batch.lexer._BatchLexer: Error: could not match input
java.lang.Error: org.intellij.lang.batch.lexer._BatchLexer: Error: could not match input
	at org.intellij.lang.batch.lexer._BatchLexer.zzScanError(_BatchLexer.java:542)
	at org.intellij.lang.batch.lexer._BatchLexer.advance(_BatchLexer.java:983)
	at com.intellij.lexer.FlexAdapter.locateToken(FlexAdapter.java:95)
	at com.intellij.lexer.FlexAdapter.getTokenType(FlexAdapter.java:58)
	at com.intellij.lexer.DelegateLexer.getTokenType(DelegateLexer.java:50)
	at com.intellij.lexer.LayeredLexer.activateLayerIfNecessary(LayeredLexer.java:70)
	at com.intellij.lexer.LayeredLexer.advance(LayeredLexer.java:161)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.documentChanged(LexerEditorHighlighter.java:241)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:795)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:731)
	at com.intellij.openapi.editor.impl.DocumentImpl.insertString(DocumentImpl.java:504)
	at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaretNoScrolling(EditorModificationUtil.java:132)
	at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaret(EditorModificationUtil.java:97)
	at com.intellij.openapi.editor.EditorModificationUtil.insertStringAtCaret(EditorModificationUtil.java:89)
	at com.intellij.openapi.editor.EditorModificationUtil.typeInStringAtCaretHonorBlockSelection(EditorModificationUtil.java:345)
	at com.intellij.codeInsight.editorActions.TypedHandler.a(TypedHandler.java:244)
	at com.intellij.codeInsight.editorActions.TypedHandler.access$100(TypedHandler.java:64)
	at com.intellij.codeInsight.editorActions.TypedHandler$1.perform(TypedHandler.java:208)
	at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:342)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:422)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:333)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:324)
	at com.intellij.codeInsight.editorActions.TypedHandler.execute(TypedHandler.java:152)
	at com.intellij.codeInsight.lookup.impl.LookupTypedHandler.execute(LookupTypedHandler.java:91)
	at com.maddyhome.idea.vim.group.ChangeGroup$2$1.run(ChangeGroup.java:621)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at com.maddyhome.idea.vim.group.ChangeGroup$2.run(ChangeGroup.java:619)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.maddyhome.idea.vim.group.ChangeGroup.processKey(ChangeGroup.java:616)
	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.java:177)
	at com.maddyhome.idea.vim.KeyHandler.handleKey(KeyHandler.java:103)
	at com.maddyhome.idea.vim.VimTypedActionHandler$1.run(VimTypedActionHandler.java:57)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Action at the time:
viewing a batch script

IntelliJ IDEA 14.1.6
Build #IU-141.3056, built on December 21, 2015
JRE: 1.8.0_51-b16 x86
JVM: Java HotSpot(TM) Server VM by Oracle Corporation

Plugins:
com.intellij
Batch Scripts Support
FindBugs-IDEA
IdeaVIM
Jindent - Source Code Formatter
Keymap exporter
NodeJS
com.thoughtworks.gauge
net.nicoulaj.idea.markdown
org.antlr.intellij.plugin

**Comment by SimonIT** [comment]
Is this still a problem? If so, could you provide the bat file so we can reproduce the problem?
