### ISSUE TITLE
Plugin doesn't work with IDEA 2018.3

### ISSUE THREAD

**Issue by ygyg70** [aefimov/idea-batch#27]
Any plans to support the latest version?

**Comment by mselerin** [comment]
Looking at the code and it might be thoses lines that register 2 times the `BRACES` text attribute: 

https://github.com/aefimov/idea-batch/blob/0d8aa3bb19fd2218d80d96ae3943531800d2c5b7/src/org/intellij/lang/batch/editor/BatchHighlighterColors.java#L43-L48

Seems like the second one should be `BATCH.BRACKETS`, no ?

**Comment by RobFreundlich** [comment]
Does SimonIT's commit fix this? If so, how can I get a build with the fix? My workflow relies heavily on this plugin, and now that I've upgraded to IDEA 2018.3, I'm stuck!

**Comment by Vampire** [comment]
As long as @SimonIT does not create a PR and @aefimov accepts it and provides a build or fixes it in another way himself and provides a build with the fix, I guess you have to build the plugin yourself with the fix of @SimonIT applied.

**Comment by SimonIT** [comment]
I didn't tested it yet, so if I find time to test it and it works I will create a pr. (If you test it, it would be great, too)

**Comment by RobFreundlich** [comment]
There turn out to be other issues with 2018.3 that make it unsuitable for my team's environment, so I'm rolling back to 2018.2, or possibly even 2018.1.

**Comment by SimonIT** [comment]
@RobFreundlich could you paste the different stacktraces? I would try fixing them

**Comment by RobFreundlich** [comment]
@SimonIT it wasn't issues with the plugin, it was with IDEA 2018.3 in general. For example, if you have a Java appserver Run Configuration that has a gulp task as a "Before launch" action, and you debug it instead of running it, it will try to debug the gulp task too. That's just plain wrong, and totally breaks my team's ability to debug our app servers, since we use gulp tasks to copy our TS code.

So 2018.3 is a non-starter for us, which renders the Batch plugin issue kind of moot for me. I've rolled back to 2018.2 for now, and the Batch plugin works fine there.

**Comment by SimonIT** [comment]
@RobFreundlich okay

**Comment by SimonIT** [comment]
You could try out [this](https://github.com/SimonIT/idea-batch/releases/download/v1.0.8-pre/idea-batch-1.0.8-SNAPSHOT.zip) builded version.

**Comment by j-m** [comment]
Any news on this?

**Comment by Sporking** [comment]
I see this exception happening in Idea probably twice per day, despite the fact that I am not actually editing any batch files recently. For now, I am uninstalling the plugin. I would love to see this fixed!

**Comment by cezary-butler** [comment]
I think the right question is there someone to maintain it. Forking is not
a problem, taking time and effort is.

śr., 6 mar 2019 o 15:38 Igor Mukhin <notifications@github.com> napisał(a):

**Comment by SimonIT** [comment]
Like I said, I forked it and fixed the bug. But I'm not expert in writing intellij plugins and I don't have much time. If someone want help, I could add him to the maintainers. I would appreciate if some would do this
[My fork](https://github.com/SimonIT/idea-batch)

**Comment by cezary-butler** [comment]
First thing I see that will make it difficult to review, is that you’ve changed something (a new line character most likely) in all files. Because of that, it’s difficult to review actual changes you’ve made.
I would recommend reverting to previous new line character, and then maybe change it in separate pull request.

**Comment by SimonIT** [comment]
@cezary-butler done

**Comment by mmelvin0** [comment]
@SimonIT I think we're the only two people left on the planet who care to view/edit batch scripts in JetBrains IDEs. Your fork works wonderfully for me thus far.

**Comment by Vampire** [comment]
That's non-sense, but why should people that have nothing constructive to say spam the comments with empty phrases?

**Comment by MartinX3** [comment]
IntelliJ Ultimate 2018.3.6
Was editing a .java file and did an autoformat and a save of the file.

```java
java.lang.IllegalStateException: TextAttributeKey(name:'BATCH.BRACES', fallbackAttributeKey:'DEFAULT_BRACKETS')  was already registered with the other fallback attribute key: DEFAULT_BRACES
	at com.intellij.openapi.editor.colors.TextAttributesKey.mergeKeys(TextAttributesKey.java:214)
	at com.intellij.openapi.editor.colors.TextAttributesKey.lambda$getOrCreate$4(TextAttributesKey.java:200)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
	at com.intellij.openapi.editor.colors.TextAttributesKey.getOrCreate(TextAttributesKey.java:200)
	at com.intellij.openapi.editor.colors.TextAttributesKey.createTextAttributesKey(TextAttributesKey.java:187)
	at org.intellij.lang.batch.editor.BatchHighlighterColors.<clinit>(BatchHighlighterColors.java:46)
	at org.intellij.lang.batch.editor.colors.BatchColorPage.<init>(BatchColorPage.java:36)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:85)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:62)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:45)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:72)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:113)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:252)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.java:179)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:197)
	at com.intellij.openapi.extensions.ExtensionPointName.getExtensions(ExtensionPointName.java:27)
	at com.intellij.openapi.options.colors.pages.ColorSettingsPagesImpl.getRegisteredPages(ColorSettingsPagesImpl.java:28)
	at com.intellij.application.options.colors.ColorAndFontOptions.initPluggedDescriptions(ColorAndFontOptions.java:522)
	at com.intellij.application.options.colors.ColorAndFontOptions.initScheme(ColorAndFontOptions.java:514)
	at com.intellij.application.options.colors.ColorAndFontOptions.initAll(ColorAndFontOptions.java:504)
	at com.intellij.application.options.colors.ColorAndFontOptions.buildConfigurables(ColorAndFontOptions.java:368)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:95)
	at com.intellij.openapi.options.ex.ConfigurableWrapper$CompositeWrapper.getConfigurables(ConfigurableWrapper.java:254)
	at com.intellij.openapi.options.newEditor.SettingsTreeView$MyNode.buildChildren(SettingsTreeView.java:463)
	at com.intellij.ui.treeStructure.CachingSimpleNode.getChildren(CachingSimpleNode.java:39)
	at com.intellij.ui.treeStructure.SimpleTreeStructure.getChildElements(SimpleTreeStructure.java:27)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.addToCache(FilteringTreeStructure.java:66)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.addToCache(FilteringTreeStructure.java:81)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.addToCache(FilteringTreeStructure.java:81)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.rebuild(FilteringTreeStructure.java:61)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.<init>(FilteringTreeStructure.java:53)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.<init>(FilteringTreeStructure.java:44)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeBuilder.<init>(FilteringTreeBuilder.java:53)
	at com.intellij.openapi.options.newEditor.SettingsTreeView$MyBuilder.<init>(SettingsTreeView.java:796)
	at com.intellij.openapi.options.newEditor.SettingsTreeView.<init>(SettingsTreeView.java:181)
	at com.intellij.openapi.options.newEditor.SettingsDialog.treeViewFactory(SettingsDialog.java:65)
	at com.intellij.openapi.options.newEditor.SettingsEditor.<init>(SettingsEditor.java:152)
	at com.intellij.openapi.options.newEditor.SettingsDialog.<init>(SettingsDialog.java:59)
	at com.intellij.openapi.options.newEditor.SettingsDialogFactory.create(SettingsDialogFactory.java:41)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getDialog(ShowSettingsUtilImpl.java:44)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:84)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:54)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:41)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:258)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:275)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:287)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:283)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:106)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:277)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:111)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:524)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:35)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:546)
	at java.awt.Component.processMouseEvent(Component.java:6548)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3325)
	at java.awt.Component.processEvent(Component.java:6313)
	at java.awt.Container.processEvent(Container.java:2237)
	at java.awt.Component.dispatchEventImpl(Component.java:4903)
	at java.awt.Container.dispatchEventImpl(Container.java:2295)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
	at java.awt.Container.dispatchEventImpl(Container.java:2281)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4725)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:737)
	at java.awt.EventQueue$4.run(EventQueue.java:735)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:664)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by twogee** [comment]
Ditto for 2019.1 except line number change
`	at com.intellij.openapi.editor.colors.TextAttributesKey.mergeKeys(TextAttributesKey.java:215)`
